import '../styles/globals.css'
import type { AppProps } from 'next/app'
import Head from 'next/head'
import { useEffect, useState } from 'react'
import { useStore } from '../utils/zustand'
import { disconnectFromSocket, connectToSocket } from '../utils/socket'

export default function App({ Component, pageProps }: AppProps) {
 
  const setStatus = useStore(state => state.setStatus)
  useEffect(()=>{
    connectToSocket()
  },[])
 
  return (
    <>
     <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Component {...pageProps}  />
    </>
  )
}
